name: Reusable Test Template

on:
  workflow_call:
    inputs:
      test_file_name:
        description: 'The specific test file to run (e.g., src/tests/rest.test.ts)'
        required: true
        type: string

jobs:
  run-test:
    name: Test ${{ inputs.test_file_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Test File
        env:
          QASE_MODE: testops
          QASE_PROJECT_CODE: ${{ secrets.QASE_PROJECT_CODE }}
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
        # Runs the specific file passed in as a variable
        run: npx vitest run ${{ inputs.test_file_name }} --reporter=html --reporter=junit --reporter=vitest-qase-reporter --outputFile.junit=test-results.xml
        
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.job }}
          path: |
            test-results.xml
            html/
